#
# Copyright (c) 2025-present, Alessandro Gario
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: 'devshell check'
description: 'Run linting and formatting checks'

runs:
  using: 'composite'
  steps:
    - name: Install just
      shell: bash
      run: cargo install just

    - name: Update Rust
      shell: bash
      run: rustup update

    - name: Run checks
      shell: bash
      run: just check
